### ISSUE TITLE
Integrating Kathará with Docker Swarm

### ISSUE THREAD

**Issue by DiegoBulhoes** [KatharaFramework/Kathara#100]
**Is your feature request related to a problem? Please describe.**
Difficulty using Kathará with more than one worker.

**Describe the solution you'd like**
Integrating Kathará with Docker Swarm, so that containers can use all nodes quickly and easily since the responsibility for the distribution of the containers will rest with Docker Swarm.

**Describe alternatives you've considered**
Configure the lab for each machine

**Additional context**
none

**Comment by Skazza94** [comment]
Hi @DiegoBulhoes,
actually there are no plans to introduce Docker Swarm support (since there are several issues with distributing custom Docker network plugins across a cluster, and we're using our own network plugin).

However, we're actively developing a Kathará version which runs on Kubernetes (called Megalos). Source code is in [this branch](https://github.com/KatharaFramework/Kathara/tree/new_megalos). We'll merge it and create a new release (with binary files) by the end of August.

Thanks.
