### ISSUE TITLE
Standard setuptools packaging for Katharà

### ISSUE THREAD

**Issue by Baldomo** [KatharaFramework/Kathara#107]
**Is your feature request related to a problem? Please describe.**
Currently, Katharà is configured to be built for Debian-like distros. Adding support for Python's `setuptools` packaging system will make it extremely easy to distribute the module for any system, especially other Linux distros.

**Describe the solution you'd like**
To make building (and maybe packaging too) easier for other Linux distros, Katharà could switch to a `setuptools`-based wheel package, or at least offer the option to use such a packaging system (see below), which could be extremely easy to add to the existing project.

**Describe alternatives you've considered**
It could be possible to unpack the final .deb file generated from the current build process for use in other distros, but it's a hack and not efficient. Moreover, the .deb releases are only uploaded to launchpad and cannot be readily downloaded on other distros.

**Additional context**
Adding `setuptools` packaging to Katharà is as easy as including the file `setup.py` below in the src directory.
An example of working `setup.py` and distribution/installation workflow:
```python
import setuptools

setuptools.setup(
    name="Kathara",
    version="2.2.4",
    author="KatharaFramework",
    url= "https://github.com/KatharaFramework/Kathara",
    packages=setuptools.find_packages(),
    install_requires=[
        "binaryornot>=0.4.4",
        "docker>=4.0.2",
        "coloredlogs>=10.0",
        "terminaltables>=3.1.0",
        "requests>=2.22.0",
        "slug>=2.0",
        "deepdiff>=4.0.9",
        "pyroute2>=0.5.7",
        "progress>=1.5",
        "appscript>=1.1.0;sys_platform=='darwin'",
        "pypiwin32>=223;sys_platform=='win32'"
    ],
    scripts=["kathara.py"],
    python_requires=">3.4"
)
```
Packaging: `python setup.py bdist_wheel`
Installing from the .whl file: `python -m pip install <file>.whl`

**Example PKGBUILD for Arch Linux**:
For example, building and installing a fully working commit of Katharà on Arch Linux could be done with this PKGBUILD
```sh
pkgname=kathara-git
pkgver=2.2.4.r0.g85c806c
pkgrel=1
provides=("${pkgname%-git}")
install=kathara.install
arch=("any")
depends=("python-setuptools")
source=("${pkgname%-git}::git+https://github.com/KatharaFramework/Kathara.git")
sha256sums=("SKIP")

pkgver() {
    cd "${srcdir}/${pkgname%-git}"
    git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
    cd "${srcdir}/${pkgname%-git}/src/"
    python setup.py bdist_wheel
}

package() {
    cd "${srcdir}/${pkgname%-git}/src/"
    python -m pip install --root="${pkgdir}" --prefix=/usr dist/*.whl
}
```

**Comment by lorenzo93** [comment]
Hi @Baldomo 

Sorry for answering so late, we were busy with different bugs in Kathará.

I appreciate a lot your scripts for installing Kathará in other Linux distributions but you missed a point.
In order to use Docker on a Linux machine you either be `root` or your user need to be in the `docker` group. This because Docker can be used to perform privilege escalation on your machine (it is a well known problem and it is very easy to achieve).
We designed Kathará with security in mind so Kathará can run without root privileges nor being in the docker group, this because we release it as a compiled binary, so you cannot change its behavior unless you recompile it. And during the installer, we set the `setuid` bit to this binary in order to be executed as root even if your user is not in the sudoers file.

In this way, Kathará can be installed even in shared computers, like university desktops where the user does not have root access and on standard user computers it does not need any additional setup.

We don't want to release different versions of Kathará with different behaviors (your version need either to execute `kathara`  commands as root or the current user in the docker group).
If you know how to overcome this problems we would very happy to accept a PR and open Kathará to users with different Linux distributions :) but as for my knowledge the only way to achieve this is to release a packet for pacman directly as we do for apt.

**Comment by Skazza94** [comment]
Hi @Baldomo,
we're currently working on building Kathará on RPM-based and Arch-based systems.

You can check the progress in the `linux-builds` branch, under the `scripts` folder. For now, RPM build works fine. We'll start working on the Arch build.

I'm closing this issue.
Thanks, 
Mariano.
