### ISSUE TITLE
REST API endpoints for Kathara

### ISSUE THREAD

**Issue by lara29** [KatharaFramework/Kathara#113]
**Feature request**
Presently, Kathara is a CLI tool and this the only way a user can run any kathara commands. This makes it a little inconvenient when having to interface kathara with another service. Also the output of the commands is text which needs to be parsed and not very helpful.

**Solution**
Exposing rest endpoints would make it easier for another service to interact with kathara and also get the result of any command back in a format like json making it easier to consume.

Are there any plans to add Rest API capability to kathara?

Thanks!

**Comment by Skazza94** [comment]
Hi @lara29,
thanks for you request.

Our team was just talking about the same feature few days ago (we need it for some internal projects). We planned to start working on this after 2 minor features (currently in `port_forwarding` and `multiple_terminals` branches) and the RPM/Arch binary releases (in the `linux-builds` branch). Probably releasing REST APIs will take ~2 months or more, since we need to:
- refactor a lot of logic in the `cli` package
- design REST endpoints accurately, even with some auth stuff like OAuth
- implement such REST APIs (using Flask or other stuff) and think how to switch between CLI and REST APIs version

Remember that Kathará is an open-source project, so your contribution, even helping us designing the REST APIs, is accepted!

Thanks,
Mariano.

**Comment by lara29** [comment]
@Skazzino Awesome, I'm glad that your team is thinking about it. I'll see if I can dedicate some cycles to this task.

**Comment by tcaiazzi** [comment]
Hi @lara29, 
we started to work on REST API Server. 

You can find it in the rest_api branch. This is only a sperimental version, but you can start to play with it (and to contribute if you want :D)! 

Thanks, 
Tommaso
