### ISSUE TITLE
Question - Can collision domains between labs be created?

### ISSUE THREAD

**Issue by jimmad123** [KatharaFramework/Kathara#122]
Hi,

I am wondering whether it is possible to setup a collision domain bridging two different Kathara labs? 

I have looked through the manual entries and found the `[bridged]` conf option and the `kathara-labs.ext` file but can't work out a way of connecting a device in one lab to a device in another lab via a single collision domain. I figured that it might be possible to send the traffic from two devices into the same VLAN on an external network interface but ideally I'd like to avoid touching any physical device connections.

I have not submitted this as a feature request due to me not knowing whether this is an existing feature that I can't work out how to implement - I hope that is okay!

Thank you,
jimmad123

**Comment by lorenzo93** [comment]
Hi @jimmad123 ,

If you create two labs naming a collision domain with the same name this is possible without any additional change.
This can happen only if the two labs are creating by the same user on the same machine because the username is encoded in the network name.

Let me know if you manage to do it or if there are some other barriers.

Best regards
Lorenzo

**Comment by jimmad123** [comment]
Hi @lorenzo93 ,

Thank you for your prompt response. I have managed to get the link setup without any issues. I also wonder - is there any way to do this with two labs created by different users? If it is not possible then I'll be able to use a single-user method but ideally I'd like to link labs created by different users.

Kind regards,
jimmad123

**Comment by lorenzo93** [comment]
Hi @jimmad123 ,

we were planning an option (inside `kathara settings`) to enable this behaviour, but there are security issues about who can enable this flag because the settings are user specific and this can affect system wide users.
For now the best is to use the single-user method.

Best,
Lorenzo

**Comment by jimmad123** [comment]
Hi @lorenzo93 ,

Thank you for the information and help with this issue, I will now close it.

Best regards,
jimmad123
