### ISSUE TITLE
Allow xterm also with sudo

### ISSUE THREAD

**Issue by francozamp2** [KatharaFramework/Kathara#133]
If I launch a lab with the --privileged option (thus being root), no terminal windows are opened. This is the wanted behaviour, supposedly due to incompatibility with sudo, as it is clear from https://github.com/KatharaFramework/Kathara/blob/master/src/Resources/cli/command/LstartCommand.py in row 137 and 168.

Nonetheless, starting xterm with sudo appears not to be an issue on my Ubuntu installation. I kindly request to consider relaxing this limitation by removing the following lines:

135            else:
136               logging.warning("Running devices with privileged capabilities, terminals won't open!")
137                Setting.get_instance().open_terminals = False

and

167                        # Since xterm does not work with "sudo", we do not open terminals when lab.ext is present.
168                       Setting.get_instance().open_terminals = False

or at least allow forcing the enable of xterm also with --privileged

**Comment by lorenzo93** [comment]
Hi @francozamp2 ,

the reason why we disable the terminals (xterm) with the privileged flag is due to its incopatibility with Wayland.
I don't know your Ubuntu configuration, but Ubuntu until 21.04 uses X11 while from 21.04 on has moved to Wayland.
Wayland is build with security in mind, so it doesn't allow to launch graphic processes that are not owned by the current user.

On your local machine is it working probably because you didn't upgrade to latest version or you changed some default configuration to roll-back to X11.

I don't think there is a reason to change the current code this time.
Moreover, with the `connect` command it is very easy to connect to a Kathara device :)

Lorenzo
