### ISSUE TITLE
Unable to start xterm windows when using API

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#148]
Hello

I have the following simple python script

```
  file_path = os.path.abspath('.')
  lab = Lab("my lab",file_path)
  h1 = lab.get_or_new_machine('h1')
  lab.connect_machine_to_link('h1', 'A', 0)
  h1.add_meta('image', 'kathara/host')
  Kathara.get_instance().deploy_lab(lab)
  h1.connect('/bin/xterm')
```

Everything runs OK except for that I could not launch the xterm at the end. It appears that the xterm window would blip but doesn't stay on the screen.

When I run the same scenario using `kathara lstart` everything works fine.

Any suggestions?

Thanks
Peter

**Comment by Skazza94** [comment]
Hi @zhangineer,
we never tested the `Machine.connect` method from Python APIs. However, this method is not meant to be used from the APIs: Kathara APIs are designed to be used without any graphical windows (e.g. using them from SSH Server, or via Jupiter, etc).

So, I disabled the method if accessing from the Python APIs in order to prevent future issues. 

Conversely, if you want to access a device shell, you can open a tty on the same terminal where you launch the Python script.
In your example, you can change the `connect` line with this one:
```python
Kathara.get_instance().connect_tty(lab.hash, machine_name=h1.name, shell="/bin/bash")
```
Otherwise, if you want to execute commands without opening a shell, you can use the `exec` method. This method returns a generator containing tuples with stdout and stderr in `bytes`:
```python
exec_output = Kathara.get_instance().exec(lab.hash, h1.name, "/bin/bash -c ls")
try:
    while True:
        (stdout, stderr) = next(exec_output)
        stdout = stdout.decode('utf-8') if stdout else ""
        stderr = stderr.decode('utf-8') if stderr else ""
except StopIteration:
    pass
```

If your use case is different from these options, please explain it better here, so we can help you.

Thanks,
Mariano.

**Comment by zhangineer2** [comment]
hi @Skazza94, thanks for your reply
I am actually trying to have a pop-up window for each docker container. Much like what I would get when I do `kathara lstart`, which creates a terminal window for each container. But the `exec` is a work around I guess.

**Comment by Skazza94** [comment]
Hey @zhangineer,
yesterday I played a little bit with your script and the Python APIs, and I was able to open a terminal without using the `Machine.connect` method. Since the APIs are much more low-level than the CLI, you actually have to write a custom pseudo-connect method.

To achieve it, you have to execute a one-line Python script from shell which calls the aforementioned `connect_tty`. This can be done typing `python3 -c "<PYTHON CODE>"`. At this point, you have to run this command in a separate `xterm` window and that's it. You can open a `xterm` using `subprocess.Popen`.

I added a `connect` function to your example to demonstrate how it can be achieved. I took all the missing pieces from the `Setting` class, so they adapt basing on your custom configuration:
```python3
import os
import shutil
import subprocess
import sys

from Kathara.manager.Kathara import Kathara
from Kathara.model.Lab import Lab
from Kathara.setting.Setting import Setting


def connect(machine):
    command = "%s -c \"from Kathara.manager.Kathara import Kathara; " \
          "Kathara.get_instance().connect_tty('%s', '%s', shell='%s')\"" \
          % (sys.executable, machine.lab.hash, machine.name, Setting.get_instance().device_shell)
    subprocess.Popen([Setting.get_instance().terminal, "-e", command], start_new_session=True)


lab = Lab("my lab")
h1 = lab.get_or_new_machine('h1')
lab.connect_machine_to_link('h1', 'A', 0)
Kathara.get_instance().wipe()
Kathara.get_instance().deploy_lab(lab)

# Call custom connect function passing the machine
connect(h1)
# You can call it twice
connect(h1)
```

Hope this helps! 😄 
Mariano.

**Comment by zhangineer2** [comment]
Thank you @Skazza94 !! This solved my issue, I can expand this further to allow users xterm to specific devices !
