### ISSUE TITLE
How to map a docker port via API

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#150]
How do I start container with port mapped to the host machine via API ?

I tried defining a meta as `port="8080:8080"`, which does not work

I am trying to achieve the following when the container starts:

```
CONTAINER ID   IMAGE                   COMMAND   CREATED         STATUS         PORTS                    NAMES
7ae24a240098   kathara/sdncontroller   "bash"    2 minutes ago   Up 2 minutes   0.0.0.0:8080->8080/tcp   recursing_hermann
```

**Comment by zhangineer2** [comment]
after some digging, the issue is because in bridge mode, port mapping is not supported
https://docs.docker.com/network/host/

so it looks like port mapping is useless in Kathara since everything runs in network mode. 

Still looking for a workaround though... The reason I need to do port mapping is mainly for external API functions

**Comment by zhangineer2** [comment]
OK, I was able to get it finally working by enabling the bridge mode, as well adding the port mapping.

**Comment by Skazza94** [comment]
Hi @zhangineer,
yes, you also have to declare `bridged` in order to expose a port on the host. 

We also discovered this behavior recently, and we [added a warning](https://github.com/KatharaFramework/Kathara/blob/c1484453b74659e50e5dc7a49591d3cd74a94d5d/src/Kathara/manager/docker/DockerMachine.py#L200) when the user exposes a port without bridged, which is now in the `develop` branch and will be featured in the new release (really soon).
