### ISSUE TITLE
get_lab_info by lab name

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#152]
Hello

When creating the lab we have the option to give a name, however, after spinning up the network scenario, there doesn't seem to be a way to get lab information via lab name. If I have multiple labs running, how can I correctly query for lab information ? 

here is what I am using

``` 
from Kathara.manager.docker.DockerManager import DockerManager
docker_manager = DockerManager()
lab_info = next(docker_manager.get_lab_info())
lab_hash = lab_info[0]['real_lab_hash']
```

Is there a better approach to this? 

Thank you

**Comment by tcaiazzi** [comment]
Hi @zhangineer,

Unfortunately, there is no method for getting labs information directly from the lab names. 

As a workaround, you can use the  `generate_urlsafe_hash` function of the `utils` module to generate the `lab hash` from the `lab name`. Then you can use the `get_lab_info` method to get the info of the desired lab. 

See the following example:

```
from Kathara.model.Lab import Lab
from Kathara.manager.Kathara import Kathara
from Kathara import utils

lab = Lab("Test")

pc1 = lab.get_or_new_machine("pc1")
pc2 = lab.get_or_new_machine("pc2")

Kathara.get_instance().deploy_lab(lab)

lab_hash_from_name = utils.generate_urlsafe_hash("Test")

lab_info = Kathara.get_instance().get_lab_info(lab_hash_from_name)

print(next(lab_info))

Kathara.get_instance().undeploy_lab(lab_hash_from_name)
```
N.B. You can use the `Kathara` class from the `Kathara.manager.Kathara` module instead of the `DockerManager`. It is a facade class for interacting with Kathara. It acts as a proxy for the selected virtualization manager (they implement the same interface). 

However, we are working on a refactor to optimize the Python APIs and we really appreciate your feedback! 

We will surely include a new method for getting labs information from their names.

If you have other suggestions, please tell us!

Many thanks for the support, 
Tommaso

**Comment by zhangineer2** [comment]
Thanks for the update @tcaiazzi !! I can work with `generate_urlsafe_hash`
