### ISSUE TITLE
 How to use the lab.ext file

### ISSUE THREAD

**Issue by meedoed** [KatharaFramework/Kathara#175]
Hello!
I want to connect my Kathara lab to an external LAN using lab.ext. For some reason, I cannot connect the collision domain to the physical interface (ping does not pass). Could you give me an example of setting up a lab with a single computer with a lab.ext file?

**Comment by Skazza94** [comment]
Hi @meedoed,
could you please share you lab configuration (`lab.ext`, `lab.conf`) and which interface you want to connect (output of the `ip link` command)? 

Thanks.

**Comment by meedoed** [comment]
![image](https://user-images.githubusercontent.com/61783125/177369227-2706d06c-1c40-439f-a72b-750a34f679b2.png)

![image](https://user-images.githubusercontent.com/61783125/177369306-d3e44981-ba82-468d-be98-fdb848e150d6.png)
![image](https://user-images.githubusercontent.com/61783125/177369425-8a74762a-217c-4e7a-9c67-04d17d775546.png)

**Comment by Skazza94** [comment]
Hi @meedoed,
configuration seems correct. Could you please start the lab and show the `ip link` output of the bridge associated to the collision domain `A` (starting with `kt-`), and also what's the problem (a `ping` output)?

**Comment by meedoed** [comment]
I assign an ip address to the ens33 interface and try to ping it. Maybe I'm doing something wrong?
![image](https://user-images.githubusercontent.com/61783125/177422184-adad060c-9fa4-4d9d-abca-21093e6bf125.png)
![image](https://user-images.githubusercontent.com/61783125/177422221-06ea0aa2-68d1-4274-a32b-24aff5849556.png)

**Comment by Skazza94** [comment]
Hi @meedoed,
the host configuration seems correct. The interface is correctly connected to the bridge.
What is the configuration of the `eth0` inside `pc`? An output of `ip route` and `ifconfig` should be ok.

Thanks, and sorry for all these questions 😄

**Comment by meedoed** [comment]
![image](https://user-images.githubusercontent.com/61783125/177424165-c7ad31b7-b8ff-4cec-89f3-44090f8849bf.png)
![image](https://user-images.githubusercontent.com/61783125/177424277-925dfda8-d36b-42ae-b2ec-dcb3e7e8c9b5.png)

**Comment by Skazza94** [comment]
Hi @meedoed,
we performed a test with the same setup you mentioned in the previous comments.

What we found is the following:
- it is not possible to ping the interface connected with the `lab.ext`. In your example, you can't ping 192.168.1.10. This is due to the fact that `ens33` is attached to the `kt-` switch, hence it loses its IP address and all its configurations (e.g. default gateway).
- you can ping IP addresses in the same subnet of `ens33`. If you have another physical device with IP 192.168.1.12, assigning to container's `eth0` an IP address in 192.168.1.0/24 subnet makes it possible to ping the .1.12
- you can use the external interface to have internet connectivity. You have to assign the original `ens33` default gateway to the device.

Hope this helps and clarifies all you problems.
If you need further help, don't hesitate to answer!

Mariano.

**Comment by meedoed** [comment]
Hi @Skazza94.
I also just ran a test already with two network cards (ens33 and ens37). With this configuration, it is possible to ping two interfaces (192.168.1.10 and 192.168.1.12). If ens37 is disabled, the ping does not pass. It turns out very interesting.

**Comment by Skazza94** [comment]
Hi @meedoed 
could you please explain better what you want to achieve? So it is easier for us to understand what's your problem and maybe give the appropriate solution.

Mariano.

**Comment by meedoed** [comment]
I just want to connect the lab to an external network. Basically, I have already solved this problem. Thank you.
