### ISSUE TITLE
Reach public Internet from a nonbridge kathara node

### ISSUE THREAD

**Issue by Ryuuba** [KatharaFramework/Kathara#194]
I'm trying to ping a public server from a nonbridged Kathara host through a bridged Kathara router. The following figure shows the network scenario I'm emulating.

![home_lan](https://user-images.githubusercontent.com/8430646/197930935-f209b75b-8169-4aa7-80bc-33d05b3ff372.png)

I want router R1 to forward packets from nonbridged PCs to reach a public server.

The following picture shows the configuration of the router R1.

![Screenshot from 2022-10-25 23-01-54](https://user-images.githubusercontent.com/8430646/197931715-4a2af1e2-4ae9-4ca7-9a3f-77c8448293b6.png)

**Comment by tcaiazzi** [comment]
Hi @Ryuuba, 

this happens since the router needs to NAT the IP address of pc*. 
Otherwise, two things can happen: 
1. The OS of the host is configured to drop packets whose the Source IP address do not match any entry of the host's routing table.
2. Even if the OS of the host is configured to route the traffic anyway, the Internet is not able to reach back the IP of pc*.

To implement the NAT, you can use the following `iptables` command on the router:
```
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
```
Note that `eth1` is the name of the bridged interface on the router.

I attach to you a small example lab to show how to configure your use case: [kathara-nat-bridged.zip](https://github.com/KatharaFramework/Kathara/files/9868728/kathara-nat-bridged.zip) 

Let me know if you need further help!
Tommaso.

**Comment by Ryuuba** [comment]
Your example shows exactly what I wanted. I appreciate your help so much. Thanks.
