### ISSUE TITLE
Use Kathará without disabling firewalld

### ISSUE THREAD

**Issue by barthr** [KatharaFramework/Kathara#201]
**Describe the bug**
Playing around with kathara and a couple of labs, none of the networking between containers seem to work, having tried the most basic example by directly connecting two hosts and receiving a 100% packet loss on ping. I'm running fedora 37
```
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:45 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:25 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

It looks like an issue with docker networking, having tried to use bridged as well but that doesn't solve it.

**Comment by Skazza94** [comment]
Hi @barthr and thanks for choosing Kathará! 😄 

Did you try to stop the `firewalld` service (running `sudo systemctl stop firewalld`) before using Kathará as suggested in our [installation guide for Red-Hat-based distros](https://github.com/KatharaFramework/Kathara/wiki/Linux#red-hat-based)?

Thanks,
Mariano.

**Comment by tcaiazzi** [comment]
Hi @barthr, 

Any news? Have you resolved your issue? 

Cheers, 
Tommaso

**Comment by barthr** [comment]
Hi, @Skazza94 and @tcaiazzi. That indeed resolved my issues, however I am having the same issues on Ubuntu (seperate system). Going to disable the firewalld to see if that resolves the issues on ubuntu. In general disabling your firewalld (I suppose) is not really recommended, so I am going to look into some iptable rules to see if it is possible to turn of firewalling for docker containers.

**Comment by Skazza94** [comment]
Hi @barthr,
thanks for the reply.

I agree that disabling `firewalld` is not the optimal solution. If you can find a way to whitelist the installed iptables rules, we'll be happy to integrate it in Kathará!

**Comment by tcaiazzi** [comment]
Hi all, 

With the new version of Kathará ([3.7.0](https://github.com/KatharaFramework/Kathara/releases/tag/3.7.0)) we released a new Docker Network Plugin based on VDE.

The [VDE plugin](https://github.com/KatharaFramework/NetworkPlugin/tree/main/vde) is set as default. With this plugin when Docker creates networks, a new VDE switch process is created for each required LAN. 
In this way, we overcome many limits of the old plugin (which uses Linux Bridges) and there is no more the need to disable `firewalld` to use Kathará.

So, I'm closing the issue since the problem should be resolved, but feel free to re-open it, if needed.

Tommaso.
