### ISSUE TITLE
Add filesystem abstraction

### ISSUE THREAD

**Issue by tcaiazzi** [KatharaFramework/Kathara#205]
We need to add a filesystem abstraction to the [Lab](https://github.com/KatharaFramework/Kathara/blob/main/src/Kathara/model/Lab.py) and [Machine](https://github.com/KatharaFramework/Kathara/blob/main/src/Kathara/model/Machine.py) classes to decouple the execution of Kathará from having a path on the host filesystem.

This will enable users to use Kathará API to fully configure a network scenario. 

We plan to use the [PyFilesystem2](https://github.com/PyFilesystem/pyfilesystem2) library to add a `fs` variable representing the filesystem abstraction to `Lab` and `Machine` classes.

**Comment by Skazza94** [comment]
Temptative Roadmap:
- [x] Introduce `pyfilesystem` into `Lab` and `Machine` classes
- [x] `Lab`: if constructor is called with `path` parameter, it means that it has a host folder in the OS filesystem (use `osfs://`). Otherwise, create an in-memory folder using `mem://` filesystem. 
- [x] Change `Lab` class to support new `pyfilesystem` reference, stored in `fs`.
- [x] Change `Machine` to reference the device folder by using the `Lab.fs` attribute, stored in `fs`.
- [x] Change the `Machine.pack_data` in order to create the tar file from the `Machine.fs` attribute.
- [x] Add a mixin `FilesystemMixin` that is inherited by `Lab` and `Machine`.
- [x] Add utility methods to `FilesystemMixin ` to add a file in the filesystem reference:
  - [x] Create `FilesystemMixin.create_from_string(value: str, dst_path: str)` that creates a file in the specified full destination path, with the content of the `value` parameter.
  - [x] Create `FilesystemMixin.create_from_path(src_path: str, dst_path: str)` that creates a file in the specified full destination path, copying the content of the file in `src_path`.
  - [x] Create `FilesystemMixin.create_from_stream(stream: IO, dst_path: str)` that creates a file in the specified full destination path, writing the content of the `stream` parameter.
- [x] Remove `shared_startup_filename` and `shared_shutdown_filename` from `Lab` constructor and recompute them everytime, so that if the file is added later it will be correctly uploaded.
- [x] Remove `startup_filename` and `shutdown_filename` from `Machine` constructor and recompute them everytime, so that if the file is added later it will be correctly uploaded.
- [x] Add docs strings to `FilesystemMixin` class.
- [x] Add unit tests for `FilesystemMixin` class.

**Comment by tcaiazzi** [comment]
We also need to add a method to the Lab class for writing the contents of the filesystem of a lab object into a path in the host filesystem.  

In this way a user can create a laboratory using the Python API and then write its content to the filesystem.
