### ISSUE TITLE
Terminal crashes if startup script output contains text that cannot be parsed as UTF-8

### ISSUE THREAD

**Issue by fstachura** [KatharaFramework/Kathara#208]
**Describe the bug**
Kathara terminal crashes if startup script output contains text that cannot be parsed as UTF-8

**To Reproduce**
1. Create directory structure as shown in below
2. Run `kathara lstart`
3. `pc1` terminal should show up and immediately crash with an error shown on screenshot below.

`$ tree`:
```
.
├── lab.conf
├── pc1/
│   └── a
├── pc1.startup
└── shared/
```

`pc1/a`:
```
test ó
```

`lab.conf`:
```
pc1[0]=A
```

`pc1.startup`:
```
cat /hostlab/pc1/a
```

Note that contents of `pc1/a` are not valid UTF-8:

`cat pc1/a | xxd`:
```
00000000: 7465 7374 20f3 0a                        test ..
```

`file -i pc1/a`
```
pc1/a: text/plain; charset=iso-8859-1
```

`iconv -t utf-8 pc1/a`
```
test iconv: illegal input sequence at position 5
```

**Expected behavior**
Kathara terminal renders text from `pc1/a`, starts the shell and stays open.

**Screenshots**

Error (visible for <1 second):

![error](https://user-images.githubusercontent.com/55913800/227794348-6f53910a-9e4f-4610-9795-33300395bf85.png)
![windows-error](https://user-images.githubusercontent.com/55913800/227801222-a4f9153c-734d-4725-97d8-68379dcebed4.png)

<details>
<summary>"check" Command Output</summary>

```
*       Current Manager is: Docker (Kathara)
*       Manager version is: 23.0.1
*       Python version is: 3.10.7 (main, Dec 28 2022, 15:08:11) [GCC 12.2.0]
*       Kathara version is: 3.5.5
*       Operating System version is: Linux-6.1.15-1-lts-x86_64
*       Trying to run `Hello World` container...
Deploying devices...|###################################################################################################################################################################################################################################################| 1/1
*       Container run successfully.
Deleting devices...|####################################################################################################################################################################################################################################################| 1/1
```
</details>

Tested on Arch Linux (updated today) and Windows 10

**Comment by tcaiazzi** [comment]
Hello @fstachura, 

Sorry for the late reply and thanks for opening the issue. I'm happy to help you! 

However, I tried to run a lab like the one you suggest, but I didn't receive any error. 

![image](https://user-images.githubusercontent.com/26346836/228498722-bb34693f-869f-4fad-9d6b-97f119e63ee0.png)

Can you please attach a copy of your lab so that I can investigate further?

Many thanks,
Tommaso

**Comment by fstachura** [comment]
Hello, 
here is a copy of the lab:

[lab.zip](https://github.com/KatharaFramework/Kathara/files/11137091/lab.zip)

**Comment by tcaiazzi** [comment]
Hi @fstachura, 

Thanks for the lab. I stared to fix the problem on this branch: [209-waiting-startup-on-connect](https://github.com/KatharaFramework/Kathara/tree/209-waiting-startup-on-connect).

We have this error since the current version of Kathará manages the print of the startup logs on the terminal directly in Python and using the 'utf-8' encoding. 

The new version will manage the print on the container, using its locale and preventing the terminal emulator from crashing. 

Thanks for the help, 
Tommaso
