### ISSUE TITLE
Errore installazione

### ISSUE THREAD

**Issue by massimorosselli** [KatharaFramework/Kathara#23]
Buonasera, sto provando ad installare Kathara su Wiindows 10 Professional.
Credo di aver fatto tutto correttamente ma credo di avere qualche problema con Docker, ma non ne sono sicuro.
Purtroppo non ho seguito le lezioni quindi non so dove mettere le mani.

Attendo aiuto...

ps. in allegato il messaggio di errore presentato.

![errore](https://user-images.githubusercontent.com/44647676/47803865-b71cf900-dd33-11e8-86c0-60cdeeaaa31a.jpg)

**Comment by lorenzo93** [comment]
Hi @massimorosselli,

you are using windows containers instead of default (linux) container.
Please swtich to linux containers and check again

**Comment by massimorosselli** [comment]
Purtroppo mi dà errore.. quando provo a fare lo switch to linux container, mi da il seguente errore..

=======ERRORE====================================================

Unable to start: Il comando in esecuzione è stato interrotto perché la variabile di preferenza "ErrorActionPreference" o il parametro comune è impostato su Stop: Impossibile avviare 'MobyLinuxVM'.

Impossibile avviare la macchina virtuale 'MobyLinuxVM' perché uno dei componenti di Hyper-V non è in esecuzione.

Impossibile avviare 'MobyLinuxVM'. (ID macchina virtuale 01696CBD-1384-4683-9FAC-F5EEB138B328)

Servizio Virtual Machine Management: impossibile avviare la macchina virtuale 'MobyLinuxVM' perché uno dei componenti di Hyper-V non è in esecuzione (ID macchina virtuale 01696CBD-1384-4683-9FAC-F5EEB138B328).
in Start-MobyLinuxVM, <Nessun file>: riga 300
in <ScriptBlock>, <Nessun file>: riga 395
   in Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:riga 36
   in Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:riga 275
   in Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:riga 59

**Comment by Kidel** [comment]
Hi. This seems to be an error with Docker.
I would suggest you try to uninstall it, removing your settings, and later
reinstall it **making sure to NOT use windows containers**. This way it
should install all the required components for Linux containers.
Also make sure that your Windows OS is up to date.

If you still have the same error, please consider checking solution on
Google:
https://www.google.it/search?q=Docker+failed+to+start%3A+%27MobyLinuxVM%27+because+one+of+the+Hyper-V+&client=ms-unknown&sourceid=chrome-mobile&ie=UTF-8


Unfortunaly we are currently unable to replocate your issue, since it does
not depend on our code but on your environment.

**Comment by massimorosselli** [comment]
Ora mi dà questo errore...

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by Kidel** [comment]
Docker is not running.
Run Docker and, just in case, `lwipe`
