### ISSUE TITLE
Can't start frr.service

### ISSUE THREAD

**Issue by buonhobo** [KatharaFramework/Kathara#248]
### Operating System

Arch Linux

### Kathará Version

3.7.0

### Bug Description

I tried to use [this lab](https://github.com/KatharaFramework/Kathara-Labs/tree/main/main-labs/intradomain-routing/frr/rip) which includes an frr configuration for rip.

I start the machines and when I try to run `systemctl start frr.service` inside any of them it just hangs for a couple of minutes and then it stops without actually starting ripd.

I checked `/usr/lib/systemd/system/frr.service` and apparently it's trying to run `/usr/lib/frr/frrinit.sh start`.
I tried to run it manually and this was the output:

```shell
root@r3:/# /usr/lib/frr/frrinit.sh start
Starting watchfrr with command: '  /usr/lib/frr/watchfrr  -d  -F traditional   zebra mgmtd ripd staticd'.
fork(): Cannot allocate memory
Failed to start watchfrr! ... failed!
```

I checked the available memory using `free -m` and it shows that I have 10+ GB of available memory.
This is not working on both my Arch Linux computers, I tried on both linux 6.5.8 and linux-lts 6.1.59.
Docker should be configured correctly on my machine, since `kathara check` works and my user is in the `docker` group.
This is also not working on my friend's laptop, which is running Fedora.

My previous lab experience with static routing worked flawlessly.

I still need to try this on Windows, but I expect it will work, since it worked for my classmates.

### Steps To Reproduce

\

### Expected Behavior

\

### Check Command Output

```shell
❯ kathara check
*	Current Manager is: Docker (Kathara)
*	Manager version is: 24.0.6
*	Python version is: 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
*	Kathara version is: 3.7.0
*	Operating System version is: Linux-6.5.8-arch1-1-x86_64
*	Trying to run `Hello World` container...
Deploying devices...|#############################################################################################| 1/1
*	Container run successfully.
Deleting devices...|##############################################################################################| 1/1
```

**Comment by lorenzo93** [comment]
Hello @BuonHobo,

We're familiar with the issue you mentioned, as it has been addressed [here](https://github.com/KatharaFramework/Kathara-Labs/issues/31).
Notably, that issue refers to the older /etc/init.d method to initiate services.
Since Kathará now utilizes systemctl, could you verify if the proposed solution is effective in your situation? Simply prepend `su` before running the service, like this: `su systemctl start frr`.

**Comment by buonhobo** [comment]
Thank you for your help.

Running `su systemctl start frr` gave this output:
```shell
root@r3:/# su systemctl start frr
su: user systemctl does not exist or the user entry does not contain all the required fields
```

But this command seems to work as expected:
```shell
root@r5:/# su -c "systemctl start frr"
root@r5:/# systemctl status frr
frr.service - FRRouting
    Loaded: loaded (/usr/lib/systemd/system/frr.service, enabled)
    Active: active (running)
```

Thank you again for your support!
Is there anything I can do to help you find a solution?

**Comment by lorenzo93** [comment]
We already tried to find a solution without any luck.
If you find the real cause of this issue we would be happy to fix it.
In the meantime, I'll write your solution even under the [original issue](https://github.com/KatharaFramework/Kathara-Labs/issues/31) so that if someone have the same problem he could learn the workaround.
We'll keep this issue open until the problem will be fixed.

Thanks for the support :)

**Comment by buonhobo** [comment]
I tried digging around but I haven't found a reason why this happens.

However, there's a simple way to include the workaround in kathara so that users don't have to know about it and can follow the lectures without issues.

It's pretty simple, it only requires adding a file named `/etc/systemd/system/frr.service.d/workaround.conf` in the kathara image. I tested the fix by adding this file inside each machine in the lab folder.

This is the file's content:
```shell
[Service]
ExecStart=
ExecStop=
ExecReload=
ExecStart=/usr/bin/su -c "/usr/lib/frr/frrinit.sh start"
ExecStop=/usr/bin/su -c "/usr/lib/frr/frrinit.sh stop"
ExecReload=/usr/bin/su -c "/usr/lib/frr/frrinit.sh reload"
```

This will override the default frr systemd unit so that it wraps the command with `su`. This solution is still a workaround, but it is easy to revert and it makes my machine work as intended.

**Comment by tcaiazzi** [comment]
Hi @BuonHobo, 

Many thanks for the help! We really appreciate it, and we will include your workaround in the next release of the `kathara/frr` image. 

I'm closing this issue, since I opened a new one (KatharaFramework/Docker-Images#10) in the Docker images repository. We can continue the discussion there. 

Many thanks for the help and support :rocket:
