### ISSUE TITLE
PROBLEM ON UBUNTU (VIRTUAL BOX) INSTALLATION

### ISSUE THREAD

**Issue by simone-liotta** [KatharaFramework/Kathara#25]
I'm installing Kathara on Ubuntu in VirtualBox (i'm not used to work with linux systems).
I've followed exactly ALL the steps mentioned in wiki (step by step). Precisely i've executed these commands on my bash:

1) curl -fsSL https://get.docker.com -o get-docker.sh
2) sudo sh get-docker.sh
3) sudo apt install python
4) sudo apt install build-essential
5) sudo apt install xterm
6) i've downloaded kathara 3.3 (source code tar.gz), i've extracted it in a folder called "kathara" and i've pasted this folder into the "opt" folder. So into my "opt" folder there is a folder called "kathara".
7) export NETKIT_HOME=/opt/kathara/bin
8) $NETKIT_HOME/install

After the 7) and 8) steps it downloads the image, so now executing again it i have this response:

![image](https://user-images.githubusercontent.com/44676159/47861406-0b3ae280-ddf3-11e8-8fc5-7d62478b81ea.png)

python is installed (2.7):

![image](https://user-images.githubusercontent.com/44676159/47861708-a6cc5300-ddf3-11e8-9638-5ae994c19f62.png)

docker-CE is installed: 

![image](https://user-images.githubusercontent.com/44676159/47861761-cd8a8980-ddf3-11e8-9049-4a073095e3c3.png)

docker (?) i don't know 

![image](https://user-images.githubusercontent.com/44676159/47861807-eb57ee80-ddf3-11e8-8bdb-51fe0e58922e.png)

Although this, when i try to execute vstart command (e.g) it doesn't work.

![image](https://user-images.githubusercontent.com/44676159/47861955-4e498580-ddf4-11e8-99c9-3f5a1a2f8c77.png)

Why? Let me know please, thanks.

**Comment by Kidel** [comment]
Try `$NETKIT_HOME/vstart --eth=0:A pc1`

Your system fails to find `vstart` because it doesn't know where it's located, so you have to use the full path (`$NETKIT_HOME/vstart`) or add $NETKIT_HOME to your $PATH.

Also since you mentioned that you're not used to Linux, let me remind you that Kathará is compatible with Windows 8+ 64bit and Mac.

**Comment by simone-liotta** [comment]
No it doesn't work i've this message.
 
![image](https://user-images.githubusercontent.com/44676159/47864319-915a2780-ddf9-11e8-9934-472994239c1b.png)

I know that kathara is compatible with windows 10 pro. But I have the home edition.

I think that kathara isn't installed when execute "kathara" it say that's not found:

![image](https://user-images.githubusercontent.com/44676159/47864345-a8991500-ddf9-11e8-9f0a-21ea68d92202.png)

**Comment by Kidel** [comment]
You didn't copy my command. vstart alone won't work if you don't use any parameter (what is it supposed to start?).

Also there is no executable called "kathara", so the second command doesn't work because it's not supposed to work.

From the outputs you gave, it seems that Kathará is installed and working well. You simply need to use the correct commands.

**Comment by simone-liotta** [comment]
ok, it's right, excuse me. thanks a lot.

**Comment by Kidel** [comment]
It's fine. Closing
