### ISSUE TITLE
problem example application dns

### ISSUE THREAD

**Issue by EmanueleBarbalaco** [KatharaFramework/Kathara#26]
![prob](https://user-images.githubusercontent.com/40856154/48130713-d369ea00-e28d-11e8-83f1-f1f87e995bd1.JPG)

When starting with the lstart command, the following errors are reported

**Comment by Kidel** [comment]
Please try `lwipe` to reset the internal state. You probably used `lstart` when your lab had only pc2 and pc1 (or they were the only ones started successfully) and now you're trying to use `lstart` again before `lclean`. 

The correct series of command is `lstart` followed by `lclean`, and **never** `lstart` followed by another `lstart`.

**Comment by EmanueleBarbalaco** [comment]
![prob](https://user-images.githubusercontent.com/40856154/48135003-fd2a0d80-e29b-11e8-9279-51bfc95e5e94.JPG)

now returns this error

**Comment by EmanueleBarbalaco** [comment]
in the snapshot you see lclear, but even typing lclean returns the same error Traceback...

**Comment by Kidel** [comment]
"lclear" does not exist. The command is "lclean" (however lwipe contains lclean).

It seems however that you now have a permissions error. Can you please copy the full output of `lstart`?

**Comment by EmanueleBarbalaco** [comment]
![prob](https://user-images.githubusercontent.com/40856154/48135797-35325000-e29e-11e8-9374-df72a25a7c1f.JPG)

**Comment by Kidel** [comment]
Please do not put Katharà labs in `/opt` (it's a system folder!).
Use a subdirectory in your user home for labs (unless you are logged in as root, but you shouldn't). 

Katharà has to run with user permissions and normal users cannot write in system folders. 

Katharà itself can be in `/opt` (and should be, since Katharà is similar to a system program), but your labs should be in a user directory. 

So
`/opt/Kathara` for the program
`/home/YOURUSERNAME/labs` (example) for your labs


**Also be sure that all files of your lab have read and write permissions.**

**And since you used `lstart`, please be sure to run `lclean` before moving the lab, or `lwipe`.**

**Comment by EmanueleBarbalaco** [comment]
![prob1](https://user-images.githubusercontent.com/40856154/48140354-dd4d1680-e2a8-11e8-9071-4d3475a892da.JPG)

**Comment by Kidel** [comment]
I can confirm you that the lab works. The problem lies with the permissions you have on those lab files. 
Try running 
`sudo chmod -R 777 /home/LAB/*`
And later `lrestart` (that is `lclean`+`lstart`)

**Comment by EmanueleBarbalaco** [comment]
![ris](https://user-images.githubusercontent.com/40856154/48141199-a972f080-e2aa-11e8-9349-891dd059c1fe.JPG)
It is ok.
Thaks for your help.

**Comment by Kidel** [comment]
No problem :)
