### ISSUE TITLE
Critical Error While Deploying Colision Domains

### ISSUE THREAD

**Issue by Binary-Phantom** [KatharaFramework/Kathara#301]
### Operating System

Kali GNU/Linux Rolling  Linux 6.8.11-amd64

### Kathará Version

3.7.6

### Bug Description

Just after i tried to run kathara vstart -n pc4 --eth 0:A the terminal gives me a error saying: 
![image](https://github.com/user-attachments/assets/76bf7478-3977-44c7-ba64-dc68dae79949)

and i cannot use the aplication

### Steps To Reproduce

my steps where:

get a custom image from my professor: sudo docker pull adrianoantunesp/kathara  
then:
kathara settings
Option 2: option 10 -> choose another image
adrianoantunesp/kathara
Option 5: option 2 -> gnome
Option 10: option 1 -> kathara/rnp
Option 11: option 1 -> yes
Option 12: option 1 -> yes

### Expected Behavior

i expected the deployment of the colision domains

### Check Command Output

```shell
Current Manager is:             Docker (Kathara)
Manager version is:             20.10.25+dfsg1
Python version is:              3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0]
Kathara version is:             3.7.6
Operating System version is:    Linux-6.8.11-amd64-x86_64
[Deploying devices]   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1
[Deleting devices]   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1
✓ Container run successfully.
```

**Comment by tcaiazzi** [comment]
Dear @Binary-Phantom, 

Thanks for reaching out! 

The error you are encountering is due to the use of an outdated version of Docker: `docker.io`. Unfortunately, there are some incompatibilities between `docker-py` (the official Docker APIs for Python) and `docker.io`. 

To fix the error, you simply need to install the newer version of Docker Engine (also known as `docker-ce`). 

You can follow the official installation guide provided by Docker: https://docs.docker.com/engine/install/

From the guide: “If you use Debian derivatives such as `BunsenLabs Linux`, `Kali Linux` or `LMDE` (Debian-based Mint) should follow the installation instructions for [Debian](https://docs.docker.com/engine/install/debian/), substitute the version of your distro for the corresponding Debian release. Refer to the documentation of your distro to find which Debian release corresponds with your derivative version.”

Please let me know if this helps.

Thanks,
Tommaso

**Comment by Binary-Phantom** [comment]
@tcaiazzi 
Thanks for your fast answer! It worked very well.
