### ISSUE TITLE
DockerFiles

### ISSUE THREAD

**Issue by jrobert2** [KatharaFramework/Kathara#36]
I've played with creating my own docker images, starting from a ubuntu image instead of kathara/netkit_base. It looks like it works perfectly, but i'm wondering if i'm wrong or not, especially since i didn't find the dockerfile of kathara/netkit_base. Could you provide it ? 

By the way, for my usage (teaching), i would find it great to have a way to specify a dockerfile inside the lab configuration (extending machine.startup for example).
Here is a use-case. I have different labs with different packages installed inside the containers. 
I could pre-create the corresponding images. It is fine, but quite complicated in terms of administration, and hardly reproducible by my students at home.
I could also have "apt install" in the startup files. But it would make the container slow to restart after crashing, while with docker images, it is cached.

Best,

Julien

**Comment by Kidel** [comment]
Hi, thanks for writing us. 


Would it be okay if we allowed to specify the root of a DockerHub image in the config?
At the moment if you use the `image` parameter in lab.conf, Docker will look for `kathara/imagename` on your machine or on DockerHub. We can allow a configuration entry to specify the root repository on the hub (that can also be an empty string, allowing you to write a full path in your lab.conf).

This way you can simply build your dockerfiles and send them to DockerHub, making the lab deployment way faster (since you don't have to build the images from scratch every time, and you don't depend on repository uptimes and versions). 

A workaround that can work even right now is basically to send your pre-built images to your DockerHub repository and have a script that downloads them locally and tags them as `kathara/something` (just locally). This way if you use `pc[image]=something` in your lab.conf, Docker will recognise the local tag, even if the remote tag on DockerHub is different.

About our dockerfile for netkit_base, I'm afraid it doesn't exist anymore. We had an issue with a package that wasn't available on a stable repository, so we switched to a pre-built version of our previous dockerfile during the development. It's not an issue since DockerHub provides a decent versioning system and we can commit changes and update the image just fine. It's actually useful since we don't have issue related to build problems. 

Hope it helps. Please tell us if the suggested solution can be sufficient for you.

**Comment by jrobert2** [comment]
Hi, thanks you for your answer. 

Yes, this solution would do ! Especially with the possibility to use local/private registry (i don't want to pollute dockerhub with all of my things). 
However i think that my colleagues would have more difficulties doing this way rather than having everything in the same lab conf.

Regarding the DockerFile, i'm sorry you lost it (even if it's not a real problem, it would have served documentation). Creating my own image, do you see any problem starting from something like phusion/baseimage ? 

Best,

Julien

**Comment by Kidel** [comment]
Hi, 
I gave a bit more thought and I think there is already a solution with the current build that allows you to get the functionality you want. 

I think this is exactly what we had in mind when we forced `kathara/` as root for the images, since Docker allows easy retagging and multiple tags. We probably wanted to give a bit of image management, since Docker usually is a bit messy if you have multiple projects depending on it. 

Basically you just need to have a script with 2 lines, similar to this one (I'm using Linux, but it's similar for Windows):

```bash
#!/bin/bash
docker build --tag kathara/YOUR_IMAGE_NAME /path/to/your/dockerfile
$NETKIT_HOME/lstart -d /path/to/your/lab
```

Now you just have to use `YOUR_IMAGE_NAME` as the image for your machine.

If instead you want to use DockerHub pre-built images (for some reason), just use a script similar to this one:

```bash
#!/bin/bash
docker pull YOUR_REPO/YOUR_IMAGE_NAME
docker tag YOUR_REPO/YOUR_IMAGE_NAME kathara/YOUR_IMAGE_NAME
$NETKIT_HOME/lstart -d /path/to/your/lab
```

You can also skip the `-d /path/to/your/lab` part if you run the script from inside the lab folder (so it can be all in one package). Supposing you also have the dockerfile in the lab folder, you can use:

```bash
#!/bin/bash
docker build --tag kathara/YOUR_IMAGE_NAME . # mind the dot here at the end
$NETKIT_HOME/lstart
```

or

```bash
#!/bin/bash
docker pull YOUR_REPO/YOUR_IMAGE_NAME
docker tag YOUR_REPO/YOUR_IMAGE_NAME kathara/YOUR_IMAGE_NAME
$NETKIT_HOME/lstart
```

We should probably make a better guide about this, to include in the "Extend Katharà" part of the wiki. 

Regarding the creation of netkit_base, you probably don't need to start from phusion. We basically just took a base Ubuntu image and from there added and configured Quagga, Ryu, OpenVSwitch and most of the useful networking tools. It was done to mimic the SDNetkit base image from our older project. 

Hope it helps, I'll be waiting for your answer.

**Comment by jrobert2** [comment]
Hi,
thanks for this idea.
The thing is it would require my users to be in the docker group with the
associated superpowers, wouldn't it ? (the wrapper you provide does not
come with the build or tag keywords)
Anyway, with the "docker pull followed by docker tag" command i see how to
deploy the images !

Regarding the base image, thanks it's clear to me now !

Best,

Julien

**Comment by Kidel** [comment]
I'll see if we can add `docker build` to the wrapper (maybe only with the pipe syntax, eg: `cat dockerfile | wrapper build`).

For now you can probably configure `sudo` to give access to `docker build` to regular users.

**Comment by jrobert2** [comment]
Ok, thanks !
Anyway, with what you told me i already have a solution for my needs !

Best,

Julien

**Comment by Kidel** [comment]
Ok, thanks for your feedback!
