### ISSUE TITLE
Enable customized tap IP addresses

### ISSUE THREAD

**Issue by vitome** [KatharaFramework/Kathara#38]
I tried to reuse a lab configuration that was working under netkit. The lab was using the tap directive, to provide an exit point to internet. It seems like in Kathara the IP addresses of the IP tap are configured differently. In particular, the in the conf file there is
`boundary[0]=tap,10.10.10.1,10.10.10.2`
but the IP assigned to eth0 of boundary is 172.33.0.2/16, while the one assigned to the other end of the tap is 172.33.0.1/16
Then, I have to manually add the default route in boundary with the correct IP.
Is there a way to customize the tap IP addresses?

EDIT: after some extra effort, it seems to have understood that in Kathara the mechanism is completely different. Thanks to Docker, everything is already there for every machine: if no config is done, a subnet from 172.something is taken and used to assign IP addresses, together with a default route and a dns towards the host. Am I in the right direction?

**Comment by Kidel** [comment]
Yes you are correct. 

Usually IP addresses are changed using the *.startup files and the ifconfig command, since Docker already provides ip addresses.

At the moment Katharà cycles through subnets in order to increase the maximum number of nodes on a single lab. For this reason the default docker IP addresses must be changed using `ifconfig`. However we are revisiting this mechanism in the near future. I'd still advise to use `ifconfig`, since that methos is used in our official labs and will always be supported.

**Comment by Kidel** [comment]
Closing.
