### ISSUE TITLE
command ftp from startup

### ISSUE THREAD

**Issue by brtar96** [KatharaFramework/Kathara#45]
**Describe the bug**
It is not possible to install ftp from the startup files.

**Expected behavior**
I'd expect to use ftp after starting the lab but the command is not found.

**Comment by Kidel** [comment]
Hi, unfortunately there is no ftp server in the `netkit_base` image. 
However there are 2 ways for you to solve this issue. 

The first one is by using the startup commands. I'm attaching a lab where `vsftpd` installs successfully: 
[lab.zip](https://github.com/KatharaFramework/Kathara/files/2977438/lab.zip)

![Annotazione 2019-03-18 110430](https://user-images.githubusercontent.com/3390842/54522494-ab8e3f80-496d-11e9-995d-ae7436193266.jpg)

The trick here is to give Internet connectivity to the nodes in order to use `apt install`. You can do that in `lab.conf` using the `bridged` option. 
Please keep in mind that I did not configure the FTP server, so it doesn't start. The client can connect to the server using the IP 10.0.0.1 as you can see from the `.startup` files. 

The second way is a bit more advanced but is the best practive and gives you FTP from the startup of the containers. It consists in creating your own image starting from `netkit_base`.

The steps are in this section of the readme: https://github.com/KatharaFramework/Kathara#extend-kathar%C3%A1

**Comment by Kidel** [comment]
Did you solve your issue? I'm closing for now, please contact us again if you need.
