### ISSUE TITLE
How to access .pcap file in virtual machine Kathará from host machine

### ISSUE THREAD

**Issue by nhvlong** [KatharaFramework/Kathara#55]
Hello everyone,

I have a question about sharing file between Kathará virtual machine and host installed Docker. _How can we access a file in Kathará VM from host_? As the previous Netkit, we can access files from host by using /hosthome (shared folder between VM and host). But how about the Kathará in case access the file in VM without copying it from VM to host?

Thanks a lot.

**Comment by Kidel** [comment]
Hi,
the `hosthome` folder is still mounted from your host home. The only difference from netkit is that `hostlab` is not mounted but copied instead.

**Comment by Kidel** [comment]
A quick follow up.
The mount is disabled if you're under linux/mac and you're not using the wrapper (happens if you edited the config or you installed with `--admin`). You still get the copy of `hostlab`, while the mount of `hosthome` should be always enabled on windows (and on linux/mac if the wrapper is enabled).

**Comment by Kidel** [comment]
https://github.com/KatharaFramework/Kathara/blob/master/bin/python/netkit_commons.py#L254 

https://github.com/KatharaFramework/Kathara/blob/master/bin/wrapper/netkit_dw.c#L158
