### ISSUE TITLE
Spawn a second terminal on startup

### ISSUE THREAD

**Issue by y0k4i-1337** [KatharaFramework/Kathara#87]
**Is your feature request related to a problem? Please describe.**
In the original Netkit, if i have something like `pc1[con1]=xterm` at my `lab.conf`, it would spawn two terminals for `pc1`. This options seems not to work on Kathara or I might be missing something...

**Describe the solution you'd like**
I would like to have the same behaviour from Netkit, so I may have two terminals for chosen machines at startup. I usually use this when I want to run tcpdump and other commands in parallel (tcpdump being run in foreground to see its output).

**Describe alternatives you've considered**
I know it is possible to use `kathara connect` explicitly and have a second connection, but sometimes it is very time consuming (complex labs).

**Additional context**
None.

**Comment by lorenzo93** [comment]
Hi @mchoji 
I understand your use case, and honestly it happens also to me sometimes but I've never heard of opening two terminals on Netkit.
I'm sorry but I don't think we are going to add this option to Kathará soon.
This because, expecially in complex labs, we are even thinking about disabling the `open terminals` option by default (you can still change that behaviour in `kathara settings`).

For example, think about working with a lab with 100 devices (Kathará can handle labs even bigger than that one). Having each time 100 terminal windows means loosing lot of time waiting for them to open and loosing lot of time looking for the right window to type commands into.
Another example could be if you run Kathará on a server, or just in a linux machine without the UI, opening the terminals it is impossible in that case.

**Comment by y0k4i-1337** [comment]
I see...well, maybe I'll try to add it in a fork when I have some time then.
Just for noting, this is implemented in Netkit's `vstart` (see http://wiki.netkit.org/man/man1/vstart.1.html). Netkit allows at most 2 consoles via --con0 and --con1 options :)

@lorenzo93 I think you can close this issue. Thanks!

**Comment by lorenzo93** [comment]
Hi @mchoji 

Maybe I was not clear enough on my last reply, I'm sorry for that.
Our developer team it is not going to implement this option in the near future, but if you would like to implement it yourself and make a PR, we are always welcome to new features. :)

If you choose this option, remember also to update the Kathará man-pages in order to let others know the option.

**Comment by y0k4i-1337** [comment]
Oh, don't worry @lorenzo93! I'm gonna try to add this as soon as I can because I used to rely on it in several labs with my students. I have moved to Kathará this year so I'm still getting used to it.
I'll surely make a PR if I manage to get it to work.

Thanks for your attention!

**Comment by Skazza94** [comment]
Hi @mchoji and thanks for you issue. 
If you want to implement this, I was thinking at this solution.

Add a `lab.conf` machine option called `num_terms` which indicates how many terminals you want to open for that machine. Default is always `1` (so a terminal will always open as standard behavior, if `--noterminals` is not specified of course).

But you can do: `pc1[num_terms]=3` to open 3 terminals or `pc1[num_terms]=0` to not open any terminal for that specific machine.

Tell me what you think.

**Comment by y0k4i-1337** [comment]
Hi @Skazzino 

This seems nice and even better than the original approach used by Netkit. In fact, I particularly have never used other values for `con1` besides `xterm` to spawn a second console. Moreover, I think the behaviours provided by values like `pty`, `none` and `port` (Netkit) can be achieved by other means in Kathará.

Thanks for your suggestion!

**Comment by tcaiazzi** [comment]
Hi @mchoji , 
I impleted the "num_terms feature" as described by @Skazzino. 
For now you can use it from the source code in the multiple_terminals branch.
It will be merged in one of the next releases. 

If you test it, let us know if it works well. 

Thanks!

**Comment by y0k4i-1337** [comment]
> Hi @mchoji , 
> I impleted the "num_terms feature" as described by @Skazzino. 
> For now you can use it from the source code in the multiple_terminals branch.
> It will be merged in one of the next releases. 
> 
> If you test it, let us know if it works well. 
> 
> Thanks!
> 
> 

That's great! Thanks for your work. I will try it as soon as possible.
