### ISSUE TITLE
Python packaging using egg files

### ISSUE THREAD

**Issue by ghost** [KatharaFramework/Kathara#90]
**Is your feature request related to a problem? Please describe.**
I'm using kathara for completing university assignments and in my class, people use very different kinds of linux distributions.
However, the only supported distribution of this program is debian.
Cloning the software, installing the dependencies and running the software on a non-debian based distribution works fine, at least in my case.

So it seems the main reason for only supporting debian is the packaging of this program.

**Describe the solution you'd like**
Python allows installation of programs using easy_install or various other tools like pip, etc. .
http://peak.telecommunity.com/DevCenter/EasyInstall
It would be easier on non-debian distributions to install kathara from an egg file or some other alternative

**Describe alternatives you've considered**
I'm not very familiar with python, so I don't know of any alternatives.
I just found out, that egg files are the equivalent to jar files from the java world.

**Additional context**
As mentioned, I'm not familiar with python.
My knowledge is limited to a 30 minutes google search :)

**Comment by ghost** [comment]
As an alternative, maybe create a section in the wiki on how to run/install this program from source on linux.

Maybe just like following:

---

0. Required tools
- python3
- pip
- git

1. Clone the repository to /opt
```
cd /opt
git clone https://github.com/KatharaFramework/Kathara.git
```

2. Install all required dependencies using `pip`
```
pip install -r src/requirements.txt
```

3. Create a simple bash script to run kathara in `/usr/bin/` called `kathara`
The content of the bash script shall be
```
#!/bin/bash
python /opt/Kathara/src/kathara.py $@
```

Make sure this script is executable with the chmod command.

When you close the terminal and open it again, you should be able to run the kathara program.

---

This approach worked on my machine (arch linux) and the machine of another student (fedora)

**Comment by lorenzo93** [comment]
Hi @enei3peX ,

Kathará works mainly with Docker. By default Docker is not accessible from non root users and this could be a problem.

The packed version of Kathará set the `setuid` flag to the main executable so it can run Docker containers even without having root privileges.

Your idea to create a guide on how to execute it from source is great but it works only if one of this two option is satisfied:

1. You always run `sudo kathara` instead of just `kathara`
2. You put your user inside the `docker` group so you don't need root access to run a docker container

Although, if you know how to build a RPM package or an arch package and you are able to create a script to automatically build it, we are very happy to accept a PR adding them to our scripts and to publish also these versions.

**Comment by ghost** [comment]
I've never created an Arch PKGBUILD, however this is a perfect situation to learn it :)
If I have some free time this weekend, I'm going to invest some of it to build a PKGBUILD.

Regarding your comments on the installation guide, maybe just add those comments to the wiki section.
I'd really like to have this installation guide to simplify the installation process for future generations of students from my university.
